# Path to the folder where you will store your manually-created music playlists,
# exemption files, and suchlike. Also, lists of problematic files will be written
# here after scans.
dataPath: "C:\\your\\data\\path\\here"
# Where you store your karaoke files.
# List as many paths as you like.
karaokePaths:
    - "C:\\path\\to\\your\\karaoke\\folder"
    - "C:\\optional\\paths\\to\\your\\other\\karaoke\\folders"
# Where you store your music files.
# List as many paths as you like.
musicPaths:
    - "C:\\path\\to\\your\\music\\folder
    - "C:\\optional\\paths\\to\\your\\other\\music\\folders"
# Files with these extensions will be treated as karaoke files.
# Filenames must be in the form "Artist - Title - VENDOR.ext".
# Files that do NOT have any of these extensions will be flagged
# as problematic.
karaokeFileExtensions:
    - zip
# Files with these extensions will be treated as music files.
# Filenames must be in the form "Artist - Title.ext".
# Other files may exist in the music folders (album art, etc)
# without being flagged as problems.
musicFileExtensions:
    - mp3
    - m4a