# Path to the folder where you will store your manually-created music playlists,
# exemption files, and suchlike. Also, lists of problematic files will be written
# here after scans.
# Note that this folder is only for "permanent" data. Transient data files like
# the singers list, program state, music requests, etc, will be written to:
# %APPDATA%\FullHouse Entertainment\KaraokeManager.
dataPath: "C:\\your\\data\\path\\here"
karaoke:
  # Where you store your karaoke files.
  # List as many paths as you like.
  paths:
    - "C:\\path\\to\\your\\karaoke\\folder"
    - "C:\\optional\\paths\\to\\your\\other\\karaoke\\folders"
  # Files that match this criteria will be treated as karaoke files.
  # There must be an "artist" and "title" group, and optionally a
  # "vendor" group. You can put in other names to match filler groups.
  # Files that do not match any of the extensions will be ignored.
  # Files that do match any of the extensions must match at least one of the
  # associated regular expression, or the file will be considered problematic.
  patterns:
    - {
        extensions: [zip],
        regExp: "(.*) - (.*) - (.*)",
        groupNames: [artist, title, vendor],
      }
music:
  # Where you store your music files.
  # List as many paths as you like.
  paths:
    - "C:\\path\\to\\your\\music\\folder"
    - "C:\\optional\\paths\\to\\your\\other\\music\\folders"
  # Files with these regex patterns will be treated as music files.
  # There must be an "artist" and "title" group. You can put in other names
  # to match filler groups.
  # Files that do not match any of the extensions will be ignored.
  # Files that do match any of the extensions must match at least one of the
  # associated regular expression, or the file will be considered problematic.
  patterns:
    - {
        extensions: [mp3, m4a],
        regExp: "(.*) - (.*)",
        groupNames: [artist, title],
      }
  # Name of an optional text file (contained in dataPath) that defines a list of
  # background music songs. One per line, with the format "artist - title".
  # Anything listed in this file that doesn't match any music files found in the
  # music paths will be flagged as a problem on startup. KaraokeManager will
  # writes the full paths of the music files that match these background music
  # titles to "KaraokeManager.backgroundMusic.txt" for AutoDJ to work with. You
  # can also permanently add items to this file during runtime with the
  # "cue,[title],add" command.
  backgroundMusicPlaylistFilename: BackgroundMusicPlaylist.txt
# Config for Winamp specific stuff.
winamp:
  # Path to Winamp executable
  exe: C:\\Program files (x86)\\Winamp\\winamp.exe
  # Hotkeys for pitch change. Manually set these in PaceMaker.
  hotkeys:
    # Modifiers can be any combination of ctrl/shift/alt
    # Key values must be letters or numbers
    pitchUp: { modifiers: [ctrl, shift], key: q }
    pitchDown: { modifiers: [ctrl, shift], key: a }
    pitchReset: { modifiers: [ctrl, shift], key: z }
