# Path to the folder where you will store your manually-created music playlists,
# exemption files, and suchlike. Also, lists of problematic files will be written
# here after scans.
dataPath: "C:\\your\\data\\path\\here"
# Where you store your karaoke files.
# List as many paths as you like.
karaokePaths:
  - "C:\\path\\to\\your\\karaoke\\folder"
  - "C:\\optional\\paths\\to\\your\\other\\karaoke\\folders"
# Where you store your music files.
# List as many paths as you like.
musicPaths:
  - "C:\\path\\to\\your\\music\\folder"
  - "C:\\optional\\paths\\to\\your\\other\\music\\folders"
# Files with these regex patterns will be treated as karaoke files.
# Specifying vendorGroup is optional.
# Any files in the karaoke paths that do not match any of
# these patterns will be considered problematic.
# will
karaokeFilePatterns:
  - {
      regex: "(.*) - (.*) - (.*).zip",
      artistGroup: 1,
      titleGroup: 2,
      vendorGroup: 3,
    }
# Files with these regex patterns will be treated as music files.
# Use [[artist]] and [[title]] as placeholders.
# Other files may exist in the music folders (album art, etc)
# without being flagged as problematic.
musicFilePatterns:
  - { regex: "(.*) - (.*).[mp3|m4a]", artistGroup: 1, titleGroup: 2 }
